#!/usr/bin/env bash
# regen-dashboard.sh — regenerate tasks/DASHBOARD.md from tasks/T*.md frontmatter
#
# Idempotent. Writes only if content changed. When invoked under git
# (pre-commit hook or manual), also `git add`s the dashboard so the
# dashboard refresh rides the same commit as the underlying status flip.
#
# Reads:
#   tasks/T*.md       — story files with YAML frontmatter (id, status, epic, title)
#                       and optional `## Retry notes` section with `### Attempt N` blocks
#   tasks/epics/E*.md — epic files; basename slug used as display name
#
# Writes:
#   tasks/DASHBOARD.md
#
# Run from the project root (pre-commit invokes hooks with cwd = repo root).

set -euo pipefail

TASKS_DIR=tasks
DASH="${TASKS_DIR}/DASHBOARD.md"

[ -d "$TASKS_DIR" ] || { echo "ERROR: $TASKS_DIR/ not found (run from project root)" >&2; exit 1; }

trim() {
  local s=$1
  s=${s#"${s%%[![:space:]]*}"}
  s=${s%"${s##*[![:space:]]}"}
  printf '%s' "$s"
}

# Load epic display names: E01 -> push-verify-ci
declare -A EPIC_NAMES=()
shopt -s nullglob
for f in "${TASKS_DIR}"/epics/E*.md; do
  base=$(basename "$f" .md)
  eid=${base%%-*}
  slug=${base#*-}
  EPIC_NAMES[$eid]=$slug
done

# Parse all stories into a TSV: epic<TAB>id<TAB>status_label<TAB>title<TAB>annotation
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

for f in "${TASKS_DIR}"/T*.md; do
  [ -f "$f" ] || continue

  fm=$(awk '/^---/{c++; next} c==1' "$f")
  id=$(trim "$(printf '%s\n' "$fm" | awk -F': ' '$1=="id"{print $2; exit}')")
  status=$(trim "$(printf '%s\n' "$fm" | awk -F': ' '$1=="status"{print $2; exit}')")
  epic=$(trim "$(printf '%s\n' "$fm" | awk -F': ' '$1=="epic"{print $2; exit}')")
  title=$(trim "$(printf '%s\n' "$fm" | awk -F': ' '$1=="title"{print $2; exit}')")

  if [ -z "$title" ]; then
    base=$(basename "$f" .md)
    title=${base#T*-}
  fi

  retry_count=$(awk '
    /^## Retry notes/    { in_section=1; next }
    in_section && /^## / { in_section=0 }
    in_section && /^### Attempt/ { c++ }
    END { print c+0 }
  ' "$f")

  spec_amended=$(awk '
    /^## Retry notes/    { in_section=1; next }
    in_section && /^## / { in_section=0 }
    in_section && (tolower($0) ~ /spec amend/ || tolower($0) ~ /wrong-by-spec/) { print "1"; exit }
  ' "$f")

  case "$status" in
    done)        slabel="done" ;;
    pending)     slabel="pend" ;;
    in-progress) slabel="wip " ;;
    wontfix)     slabel="skip" ;;
    blocked)     slabel="blok" ;;
    "")          slabel="????" ;;
    *)           slabel=$(printf '%-4.4s' "$status") ;;
  esac

  ann=""
  if [ "$retry_count" -gt 0 ]; then
    if [ "$retry_count" -eq 1 ]; then
      ann="(1 retry"
    else
      ann="($retry_count retries"
    fi
    if [ "$spec_amended" = "1" ]; then
      ann="$ann · spec amended"
    fi
    ann="$ann)"
  elif [ "$spec_amended" = "1" ]; then
    ann="(spec amended)"
  fi

  printf '%s\t%s\t%s\t%s\t%s\n' "$epic" "$id" "$slabel" "$title" "$ann" >> "$TMP"
done

if ! [ -s "$TMP" ]; then
  echo "ERROR: no stories parsed from ${TASKS_DIR}/T*.md" >&2
  exit 1
fi

count_label() {
  awk -F'\t' -v lbl="$1" '$3==lbl' "$TMP" | wc -l | tr -d ' '
}

total=$(wc -l < "$TMP" | tr -d ' ')
n_done=$(count_label "done")
n_pend=$(count_label "pend")
n_wip=$(count_label "wip ")
n_skip=$(count_label "skip")
n_blok=$(count_label "blok")
n_settled=$((n_done + n_skip))

bucket_header() {
  # Args: prefix, done, total, skip, blok
  local prefix=$1 d=$2 t=$3 s=$4 b=$5
  if [ "$d" -eq "$t" ]; then
    printf '%s  [%s/%s done]\n' "$prefix" "$d" "$t"
  else
    local bits=()
    [ "$d" -gt 0 ] && bits+=("$d done")
    [ "$s" -gt 0 ] && bits+=("$s wontfix")
    [ "$b" -gt 0 ] && bits+=("$b blocked")
    local hdr=""
    local x
    for x in "${bits[@]}"; do
      if [ -z "$hdr" ]; then hdr="$x"; else hdr="$hdr · $x"; fi
    done
    [ -z "$hdr" ] && hdr="$t total"
    printf '%s  [%s]\n' "$prefix" "$hdr"
  fi
}

emit_rows() {
  awk -F'\t' '
    {
      ann=$5
      if (ann!="") ann=" "ann
      printf "  %s   %s  %s%s\n", $3, $2, $4, ann
    }
  '
}

OUT=$(mktemp)
trap 'rm -f "$TMP" "$OUT"' EXIT

{
  echo "# Tasks dashboard"
  echo
  echo "_Auto-generated by tools/regen-dashboard.sh — do not hand-edit. Source of truth: tasks/T*.md frontmatter._"
  echo
  printf '## Summary  %s done · %s wontfix · %s pending · %s blocked  (%s/%s settled)\n' \
    "$n_done" "$n_skip" "$n_pend" "$n_blok" "$n_settled" "$total"
  if [ "$n_wip" -gt 0 ]; then
    printf '_Plus: %s in-progress._\n' "$n_wip"
  fi
  echo

  # Epics first, sorted ascending by ID
  while IFS= read -r e; do
    [ -n "$e" ] || continue
    name=${EPIC_NAMES[$e]:-(unknown)}
    rows=$(awk -F'\t' -v e="$e" '$1==e' "$TMP" | sort -t$'\t' -k2,2)
    edone=$(printf '%s\n' "$rows" | awk -F'\t' '$3=="done"' | wc -l | tr -d ' ')
    etotal=$(printf '%s\n' "$rows" | wc -l | tr -d ' ')
    eskip=$(printf '%s\n' "$rows" | awk -F'\t' '$3=="skip"' | wc -l | tr -d ' ')
    eblok=$(printf '%s\n' "$rows" | awk -F'\t' '$3=="blok"' | wc -l | tr -d ' ')
    bucket_header "## $e $name" "$edone" "$etotal" "$eskip" "$eblok"
    echo
    printf '%s\n' "$rows" | emit_rows
    echo
  done < <(awk -F'\t' '$1!=""{print $1}' "$TMP" | sort -u)

  # No-epic bucket last
  norows=$(awk -F'\t' '$1==""' "$TMP" | sort -t$'\t' -k2,2)
  if [ -n "$norows" ]; then
    nodone=$(printf '%s\n' "$norows" | awk -F'\t' '$3=="done"' | wc -l | tr -d ' ')
    nototal=$(printf '%s\n' "$norows" | wc -l | tr -d ' ')
    noskip=$(printf '%s\n' "$norows" | awk -F'\t' '$3=="skip"' | wc -l | tr -d ' ')
    noblok=$(printf '%s\n' "$norows" | awk -F'\t' '$3=="blok"' | wc -l | tr -d ' ')
    bucket_header "## (no epic)" "$nodone" "$nototal" "$noskip" "$noblok"
    echo
    printf '%s\n' "$norows" | emit_rows
    echo
  fi

  echo "Legend: done | pend | wip | skip | blok"
} > "$OUT"

if ! [ -f "$DASH" ] || ! cmp -s "$OUT" "$DASH"; then
  mv "$OUT" "$DASH"
  echo "wrote $DASH"
  if git rev-parse --git-dir >/dev/null 2>&1; then
    git add "$DASH" 2>/dev/null || true
  fi
else
  echo "$DASH unchanged"
fi
