"""Shared rules for scripts/sync-codex.sh and scripts/check.py (stdlib only).

Authored sources: plugins/<p>/.claude-plugin/plugin.json and each SKILL.md.
Everything derived from them (marketplace descriptions and versions, the README
table, Codex agents/openai.yaml) is regenerated by sync-codex.sh.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CLAUDE_MARKET = ROOT / ".claude-plugin" / "marketplace.json"

SUFFIX_PORTABLE = "Portable across SKILL.md-native hosts."
SUFFIX_CC = "Claude Code only."

OPENAI_YAML_MARKER = "# Generated by scripts/sync-codex.sh"
OPENAI_YAML = (
    f"{OPENAI_YAML_MARKER} from `disable-model-invocation: true` in SKILL.md. Do not edit.\n"
    "policy:\n"
    "  allow_implicit_invocation: false\n"
)

# A host note a plugin.json description may still carry by hand. It is stripped
# before the normalized suffix is appended, so the note never appears twice.
_HOST_NOTE = re.compile(r"\s*(?:Portable across|Claude[- ]Code[- ]only|Claude-Code-leaning)\b[^.]*\.\s*$")

# A lowercase word after the period (as in "e.g. the") does not start a sentence.
_SENTENCE_BREAK = re.compile(r"(?<=[.!?])\s+(?=[A-Z0-9`'\"(\[])")

_KEY = re.compile(r"^([A-Za-z0-9_-]+):(?:\s+(.*))?$")


def is_cc(plugin):
    return plugin.startswith("cc-")


def base_description(desc):
    """The plugin.json description without any hand-written host note."""
    out = " ".join(desc.split())
    while True:
        stripped = _HOST_NOTE.sub("", out).rstrip()
        if stripped == out:
            return out
        out = stripped


def marketplace_description(plugin, desc):
    suffix = SUFFIX_CC if is_cc(plugin) else SUFFIX_PORTABLE
    return f"{base_description(desc)} {suffix}"


def sentences(text):
    return _SENTENCE_BREAK.split(" ".join(text.split()))


def readme_blurb(desc, cap=170):
    """Whole sentences of the base description up to `cap` chars, never cut mid-sentence.
    The first sentence is always kept; check.py holds it to the same cap."""
    parts = sentences(base_description(desc))
    out = parts[0]
    for part in parts[1:]:
        if len(out) + 1 + len(part) > cap:
            break
        out = f"{out} {part}"
    if not out.endswith((".", "!", "?")):
        out += "."
    return out.replace("|", "\\|")


def frontmatter(path):
    """Top-level keys of a SKILL.md frontmatter. Handles the shapes this repo uses (plain,
    quoted, folded or literal block scalars, block lists); it is not a YAML parser.
    Returns None when there is no closed `---` block."""
    lines = Path(path).read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].rstrip() != "---":
        return None
    raw, key = {}, None
    for ln in lines[1:]:
        if ln.rstrip() == "---":
            break
        if ln.startswith("#"):
            continue
        m = _KEY.match(ln)
        if m:
            key = m.group(1)
            raw[key] = ((m.group(2) or "").strip(), [])
        elif key is not None:
            raw[key][1].append(ln)
    else:
        return None
    return {k: _scalar(head, rest) for k, (head, rest) in raw.items()}


def _scalar(head, rest):
    body = [ln.strip() for ln in rest if ln.strip()]
    if head[:1] == ">":
        return " ".join(body)
    if head[:1] == "|":
        return "\n".join(body)
    if not head and body and all(ln.startswith("-") for ln in body):
        return [ln[1:].strip().strip("'\"") for ln in body]
    if len(head) >= 2 and head[0] == head[-1] and head[0] in "'\"":
        return head[1:-1]
    return " ".join([head] + body).strip()


def is_user_only(fm):
    return str((fm or {}).get("disable-model-invocation", "")).strip().lower() == "true"


def skill_files():
    """(plugin, SKILL.md path) for every skill of every plugin dir with a manifest."""
    for skill_md in sorted(ROOT.glob("plugins/*/skills/*/SKILL.md")):
        plugin_dir = skill_md.parents[2]
        if (plugin_dir / ".claude-plugin" / "plugin.json").is_file():
            yield plugin_dir.name, skill_md


def openai_yaml_wanted(plugin, fm):
    return not is_cc(plugin) and is_user_only(fm)


def openai_yaml_targets():
    """agents/openai.yaml path of every skill that must carry the Codex policy."""
    return {
        skill_md.parent / "agents" / "openai.yaml"
        for plugin, skill_md in skill_files()
        if openai_yaml_wanted(plugin, frontmatter(skill_md))
    }


def is_generated_openai_yaml(path):
    return path.is_file() and path.read_text(encoding="utf-8").startswith(OPENAI_YAML_MARKER)
